// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hostello.Data;

#nullable disable

namespace hostello.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220810195341_v4")]
    partial class v4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("EstabelecimentoResponsavel", b =>
                {
                    b.Property<int>("EstabelecimentosIdEstabelecimento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResponsaveisFkUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("EstabelecimentosIdEstabelecimento", "ResponsaveisFkUsuario");

                    b.HasIndex("ResponsaveisFkUsuario");

                    b.ToTable("EstabelecimentoResponsavel");
                });

            modelBuilder.Entity("hostello.Models.Acomodacao", b =>
                {
                    b.Property<int>("IdAcomodacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadiaMin")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MediaAvaliacaoQuarto")
                        .HasColumnType("REAL");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PessoasMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TipoAcomodacaoIdTipoAcomodacao")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ValorDiaria")
                        .HasColumnType("REAL");

                    b.HasKey("IdAcomodacao");

                    b.HasIndex("TipoAcomodacaoIdTipoAcomodacao");

                    b.ToTable("Acomodacoes");
                });

            modelBuilder.Entity("hostello.Models.Admin", b =>
                {
                    b.Property<int>("FkUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAdmin")
                        .HasColumnType("INTEGER");

                    b.HasKey("FkUsuario");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("hostello.Models.Avaliacao", b =>
                {
                    b.Property<int>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AcomodacaoIdAcomodacao")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteFkUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("TEXT");

                    b.Property<double>("NotaAvaliacao")
                        .HasColumnType("REAL");

                    b.HasKey("IdAvaliacao");

                    b.HasIndex("AcomodacaoIdAcomodacao");

                    b.HasIndex("ClienteFkUsuario");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("hostello.Models.Cliente", b =>
                {
                    b.Property<int>("FkUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.HasKey("FkUsuario");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("hostello.Models.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Cep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClienteFkUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("IdEndereco");

                    b.HasIndex("ClienteFkUsuario");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("hostello.Models.Estabelecimento", b =>
                {
                    b.Property<int>("IdEstabelecimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<double>("MediaAvaliacao")
                        .HasColumnType("REAL");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoneFixo")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.HasKey("IdEstabelecimento");

                    b.ToTable("Estabelecimentos");
                });

            modelBuilder.Entity("hostello.Models.ItemReserva", b =>
                {
                    b.Property<int>("IdItemReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AcomodacaoIdAcomodacao")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("IdItemReserva");

                    b.HasIndex("AcomodacaoIdAcomodacao");

                    b.ToTable("ItensReserva");
                });

            modelBuilder.Entity("hostello.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteFkUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EstadiaEntrada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EstadiaSaida")
                        .HasColumnType("TEXT");

                    b.HasKey("IdReserva");

                    b.HasIndex("ClienteFkUsuario");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("hostello.Models.Responsavel", b =>
                {
                    b.Property<int>("FkUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdResponsavel")
                        .HasColumnType("INTEGER");

                    b.HasKey("FkUsuario");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("hostello.Models.TipoAcomodacao", b =>
                {
                    b.Property<int>("IdTipoAcomodacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeAcomodacao")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("IdTipoAcomodacao");

                    b.ToTable("TiposAcomodacoes");
                });

            modelBuilder.Entity("hostello.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<char>("Sexo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EstabelecimentoResponsavel", b =>
                {
                    b.HasOne("hostello.Models.Estabelecimento", null)
                        .WithMany()
                        .HasForeignKey("EstabelecimentosIdEstabelecimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hostello.Models.Responsavel", null)
                        .WithMany()
                        .HasForeignKey("ResponsaveisFkUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hostello.Models.Acomodacao", b =>
                {
                    b.HasOne("hostello.Models.TipoAcomodacao", null)
                        .WithMany("Acomodacoes")
                        .HasForeignKey("TipoAcomodacaoIdTipoAcomodacao");
                });

            modelBuilder.Entity("hostello.Models.Avaliacao", b =>
                {
                    b.HasOne("hostello.Models.Acomodacao", null)
                        .WithMany("Avaliacoes")
                        .HasForeignKey("AcomodacaoIdAcomodacao");

                    b.HasOne("hostello.Models.Cliente", null)
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ClienteFkUsuario");
                });

            modelBuilder.Entity("hostello.Models.Endereco", b =>
                {
                    b.HasOne("hostello.Models.Cliente", null)
                        .WithMany("Enderecos")
                        .HasForeignKey("ClienteFkUsuario");
                });

            modelBuilder.Entity("hostello.Models.ItemReserva", b =>
                {
                    b.HasOne("hostello.Models.Acomodacao", null)
                        .WithMany("ItensReserva")
                        .HasForeignKey("AcomodacaoIdAcomodacao");
                });

            modelBuilder.Entity("hostello.Models.Reserva", b =>
                {
                    b.HasOne("hostello.Models.Cliente", null)
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteFkUsuario");
                });

            modelBuilder.Entity("hostello.Models.Acomodacao", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("ItensReserva");
                });

            modelBuilder.Entity("hostello.Models.Cliente", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Enderecos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("hostello.Models.TipoAcomodacao", b =>
                {
                    b.Navigation("Acomodacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
