// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hostello.Data;

#nullable disable

namespace hostello.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220916212343_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("EstabelecimentoResponsavel", b =>
                {
                    b.Property<int>("EstabelecimentosFkEndereco")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResponsaveisFkUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("EstabelecimentosFkEndereco", "ResponsaveisFkUsuario");

                    b.HasIndex("ResponsaveisFkUsuario");

                    b.ToTable("EstabelecimentoResponsavel");
                });

            modelBuilder.Entity("hostello.Models.Acomodacao", b =>
                {
                    b.Property<int>("FkEstabelecimento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadiaMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkTipoAcomodacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAcomodacao")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MediaAvaliacaoQuarto")
                        .HasColumnType("REAL");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PessoasMax")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ValorDiaria")
                        .HasColumnType("REAL");

                    b.HasKey("FkEstabelecimento");

                    b.HasIndex("FkTipoAcomodacao");

                    b.ToTable("Acomodacoes");
                });

            modelBuilder.Entity("hostello.Models.Admin", b =>
                {
                    b.Property<int>("FkUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAdmin")
                        .HasColumnType("INTEGER");

                    b.HasKey("FkUsuario");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("hostello.Models.Avaliacao", b =>
                {
                    b.Property<int>("FkAcomodacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("FkCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAvaliacao")
                        .HasColumnType("INTEGER");

                    b.Property<double>("NotaAvaliacao")
                        .HasColumnType("REAL");

                    b.HasKey("FkAcomodacao");

                    b.HasIndex("FkCliente");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("hostello.Models.Cliente", b =>
                {
                    b.Property<int>("FkUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkEndereco")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.HasKey("FkUsuario");

                    b.HasIndex("FkEndereco");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("hostello.Models.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("IdEndereco");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("hostello.Models.Estabelecimento", b =>
                {
                    b.Property<int>("FkEndereco")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdEstabelecimento")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MediaAvaliacao")
                        .HasColumnType("REAL");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoneFixo")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.HasKey("FkEndereco");

                    b.ToTable("Estabelecimentos");
                });

            modelBuilder.Entity("hostello.Models.ItemReserva", b =>
                {
                    b.Property<int>("FkReserva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkAcomodacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdItemReserva")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("FkReserva");

                    b.HasIndex("FkAcomodacao");

                    b.ToTable("ItensReserva");
                });

            modelBuilder.Entity("hostello.Models.Reserva", b =>
                {
                    b.Property<int>("FkCliente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EstadiaEntrada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EstadiaSaida")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdReserva")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ValorReserva")
                        .HasColumnType("REAL");

                    b.HasKey("FkCliente");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("hostello.Models.Responsavel", b =>
                {
                    b.Property<int>("FkUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdResponsavel")
                        .HasColumnType("INTEGER");

                    b.HasKey("FkUsuario");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("hostello.Models.TipoAcomodacao", b =>
                {
                    b.Property<int>("IdTipoAcomodacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeAcomodacao")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("IdTipoAcomodacao");

                    b.ToTable("TiposAcomodacoes");
                });

            modelBuilder.Entity("hostello.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<char>("Sexo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EstabelecimentoResponsavel", b =>
                {
                    b.HasOne("hostello.Models.Estabelecimento", null)
                        .WithMany()
                        .HasForeignKey("EstabelecimentosFkEndereco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hostello.Models.Responsavel", null)
                        .WithMany()
                        .HasForeignKey("ResponsaveisFkUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hostello.Models.Acomodacao", b =>
                {
                    b.HasOne("hostello.Models.Estabelecimento", "Estabelecimento")
                        .WithMany("Acomodacoes")
                        .HasForeignKey("FkEstabelecimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hostello.Models.TipoAcomodacao", "TipoAcomodacao")
                        .WithMany("Acomodacoes")
                        .HasForeignKey("FkTipoAcomodacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estabelecimento");

                    b.Navigation("TipoAcomodacao");
                });

            modelBuilder.Entity("hostello.Models.Admin", b =>
                {
                    b.HasOne("hostello.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("FkUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("hostello.Models.Avaliacao", b =>
                {
                    b.HasOne("hostello.Models.Acomodacao", "Acomodacao")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("FkAcomodacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hostello.Models.Cliente", "Cliente")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("FkCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acomodacao");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("hostello.Models.Cliente", b =>
                {
                    b.HasOne("hostello.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("FkEndereco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hostello.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("FkUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("hostello.Models.Estabelecimento", b =>
                {
                    b.HasOne("hostello.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("FkEndereco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("hostello.Models.ItemReserva", b =>
                {
                    b.HasOne("hostello.Models.Acomodacao", "Acomodacao")
                        .WithMany("ItensReserva")
                        .HasForeignKey("FkAcomodacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hostello.Models.Reserva", "Reserva")
                        .WithMany("ItensReserva")
                        .HasForeignKey("FkReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acomodacao");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("hostello.Models.Reserva", b =>
                {
                    b.HasOne("hostello.Models.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("FkCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("hostello.Models.Responsavel", b =>
                {
                    b.HasOne("hostello.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("FkUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("hostello.Models.Acomodacao", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("ItensReserva");
                });

            modelBuilder.Entity("hostello.Models.Cliente", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("hostello.Models.Estabelecimento", b =>
                {
                    b.Navigation("Acomodacoes");
                });

            modelBuilder.Entity("hostello.Models.Reserva", b =>
                {
                    b.Navigation("ItensReserva");
                });

            modelBuilder.Entity("hostello.Models.TipoAcomodacao", b =>
                {
                    b.Navigation("Acomodacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
